version: "3.4"
services:
  app_server_01:
    container_name: app_server_01
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      NUM_SERVER: 'server 01'
    networks:
      - common

  app_server_02:
    container_name: app_server_02
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/app
    environment:
      NUM_SERVER: 'server 02'
    networks:
      - common

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs/:/etc/nginx/certs/
    depends_on:
      - app_server_01
      - app_server_02
    networks:
      - common

networks:
  common:

